# Generated by Django 4.1.7 on 2023-02-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Available',
            new_name='available',
        ),
    ]
